apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      containers:
        - name: gitlab-runner-linux
          image: gitlab/gitlab-runner:latest
          env:
            - name: CI_SERVER_URL
              value: "https://gitlab.example.com/"
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-runner-secret
                  key: registration_token
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - name: config
              mountPath: /etc/gitlab-runner
          nodeSelector:
            kubernetes.io/os: linux
        - name: gitlab-runner-windows
          image: gitlab/gitlab-runner:latest
          env:
            - name: CI_SERVER_URL
              value: "https://gitlab.example.com/"
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-runner-secret
                  key: registration_token
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            - name: config
              mountPath: C:\\etc\\gitlab-runner
          nodeSelector:
            kubernetes.io/os: windows
      volumes:
        - name: config
          emptyDir: {}
