apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab
type: Opaque
data:
  registration_token: bXlfc2VjcmV0X3Rva2Vu  # Replace with your base64 encoded registration token
